### PR TITLE
Spelling/grammar errors

### PR DESCRIPTION
**Pull request by lamby**
Resolve some simple spelling and grammatical errors that ended up in the final binary.

### CODE REVIEW

**Comment by cmayer** [comment]
Many thanks!

**Comment by lamby** [comment]
Reopened?

**Comment by cmayer** [comment]
I tried to merge on my old laptop. Githut warned me that Firefox was too old. I ignored the warning and tried to merge. Nothing happend. I pressed on close and it worked - without merging. So I reopened. Now it should have worked. Thanks for your comments.

**Comment by tillea** [comment]
Did you changed only grammar and spelling or is your last commit considered a new version we can release in Debian (see #9).  Please note that the contribution from @lamby was only because BaitFisher is packaged for Debian and it would help a lot if you would consider to support our packaging attempts.
Thanks for considering, Andreas.

**Pull request merged**
